INSERT INTO issues (title, description, status, created_at, updated_at, user_id) VALUES
('Login page returns 500 error on invalid credentials',
 'Users attempting to log in with incorrect credentials are receiving a 500 Internal Server Error instead of a proper validation message. The issue appears to originate from the authentication service not properly handling null responses from the database query, resulting in an unhandled exception and degraded user experience.',
 'OPEN',
 '2026-01-05 09:13:22',
 '2026-01-05 10:02:11',
 'cmm09k0yo0000yhlkn8u71cqn'),

('Dashboard metrics not updating in real time',
 'The analytics dashboard fails to refresh key performance indicators after new data is ingested, requiring users to manually reload the page. Initial investigation suggests a caching misconfiguration in the API layer that prevents fresh data from being fetched at the expected polling interval.',
 'WIP',
 '2026-01-06 08:45:10',
 '2026-01-06 11:20:44',
 'cmm09nhyv0001yhlki9pdgkdw'),

('Email notifications not sent for new comments',
 'Users are not receiving email notifications when new comments are added to their assigned issues. Logs indicate that the message queue is receiving events, but the email service fails silently due to a misconfigured SMTP credential in the production environment.',
 'OPEN',
 '2026-01-07 14:12:33',
 '2026-01-07 15:01:09',
 'cmm0ba3qe0002yhlk8oh2utnu'),

('File upload fails for large attachments',
 'Uploading attachments larger than 10MB results in a timeout error despite the documented limit being 25MB. The reverse proxy configuration appears to enforce a lower maximum body size than intended, causing uploads to terminate prematurely without a helpful error message.',
 'WIP',
 '2026-01-08 10:05:55',
 '2026-01-08 12:47:18',
 'cmm09k0yo0000yhlkn8u71cqn'),

('Search functionality returns incomplete results',
 'The global search feature intermittently omits relevant records that clearly match the search query. This behavior is likely related to an out-of-sync search index that has not been fully rebuilt after the latest schema migration.',
 'OPEN',
 '2026-01-09 09:22:41',
 '2026-01-09 09:58:30',
 'cmm09nhyv0001yhlki9pdgkdw'),

('User profile updates not persisting',
 'Changes made to user profile information such as display name and profile picture appear successful in the UI but revert after a page refresh. Backend logs show that the update transaction is being rolled back due to a validation constraint triggered by legacy data.',
 'CLOSED',
 '2026-01-10 11:17:03',
 '2026-01-11 08:42:27',
 'cmm0ba3qe0002yhlk8oh2utnu'),

('Pagination broken on activity feed',
 'The activity feed does not properly paginate beyond the second page, resulting in repeated or missing entries when users attempt to browse older records. The issue likely stems from an incorrect offset calculation in the database query.',
 'WIP',
 '2026-01-11 13:09:48',
 '2026-01-11 16:33:12',
 'cmm09k0yo0000yhlkn8u71cqn'),

('API rate limiting not enforced consistently',
 'Certain API endpoints are bypassing the configured rate limiting middleware, allowing excessive requests from the same IP address. This inconsistency may expose the system to abuse and performance degradation under high traffic conditions.',
 'OPEN',
 '2026-01-12 07:55:29',
 '2026-01-12 09:14:52',
 'cmm09nhyv0001yhlki9pdgkdw'),

('Incorrect timezone displayed in reports',
 'Generated reports are displaying timestamps in UTC rather than the user’s configured local timezone, causing confusion when reviewing time-sensitive data. The formatting utility does not currently account for user-specific timezone preferences.',
 'CLOSED',
 '2026-01-13 10:40:16',
 '2026-01-13 12:05:37',
 'cmm0ba3qe0002yhlk8oh2utnu'),

('Password reset link expires immediately',
 'Users report that password reset links are invalid immediately after receiving them via email. Investigation shows that the token expiration time is miscalculated due to a mismatch between server time and token generation time.',
 'OPEN',
 '2026-01-14 15:18:02',
 '2026-01-14 15:59:41',
 'cmm09k0yo0000yhlkn8u71cqn'),

('Data export to CSV includes malformed headers',
 'When exporting issue data to CSV format, the generated file contains duplicated and improperly formatted column headers, making it difficult to import into spreadsheet tools. The serialization logic appears to concatenate header values incorrectly.',
 'WIP',
 '2026-01-15 09:27:54',
 '2026-01-15 11:11:23',
 'cmm09nhyv0001yhlki9pdgkdw'),

('Mobile layout breaks on iOS Safari',
 'The responsive layout of the application renders incorrectly on iOS Safari, causing overlapping buttons and truncated text in the navigation bar. The problem appears to be related to unsupported CSS flexbox properties in certain Safari versions.',
 'OPEN',
 '2026-01-16 08:34:19',
 '2026-01-16 10:22:50',
 'cmm0ba3qe0002yhlk8oh2utnu'),

('Session timeout not triggering after inactivity',
 'User sessions remain active indefinitely even after prolonged periods of inactivity, which poses a security concern. The session management middleware does not properly invalidate tokens when the inactivity threshold is exceeded.',
 'WIP',
 '2026-01-17 12:14:36',
 '2026-01-17 14:49:05',
 'cmm09k0yo0000yhlkn8u71cqn'),

('Broken link in onboarding tutorial',
 'New users following the onboarding tutorial encounter a broken link when attempting to access the documentation page. The hyperlink references a deprecated route that was removed during the last frontend refactor.',
 'CLOSED',
 '2026-01-18 09:03:11',
 '2026-01-18 10:15:42',
 'cmm09nhyv0001yhlki9pdgkdw'),

('Duplicate records created on form resubmission',
 'Submitting certain forms multiple times due to slow network conditions results in duplicate database records. The backend lacks idempotency safeguards, allowing repeated transactions to create redundant entries.',
 'OPEN',
 '2026-01-19 11:26:47',
 '2026-01-19 13:37:29',
 'cmm0ba3qe0002yhlk8oh2utnu'),

('Third-party API integration intermittently failing',
 'Integration with the external payment provider occasionally fails with a timeout error, disrupting checkout completion. Monitoring indicates that retries are not properly configured, and transient network failures are not gracefully handled.',
 'WIP',
 '2026-01-20 14:08:55',
 '2026-01-20 16:21:34',
 'cmm09k0yo0000yhlkn8u71cqn'),

('Incorrect total displayed in billing summary',
 'The billing summary page sometimes displays an incorrect total amount when multiple discounts are applied. The calculation logic does not correctly account for stacked percentage and fixed discounts in the final computation.',
 'OPEN',
 '2026-01-21 10:44:28',
 '2026-01-21 12:09:57',
 'cmm09nhyv0001yhlki9pdgkdw'),

('Websocket connection drops after deployment',
 'After each production deployment, active websocket connections are abruptly terminated and not automatically re-established, requiring users to refresh the page. The reconnection strategy on the client side is insufficient to handle server restarts.',
 'WIP',
 '2026-01-22 08:19:43',
 '2026-01-22 09:50:16',
 'cmm0ba3qe0002yhlk8oh2utnu'),

('Accessibility issues with form labels',
 'Several form inputs are missing properly associated labels, making the interface difficult to navigate using screen readers. Accessibility audits flagged these elements as failing WCAG compliance standards, requiring markup adjustments.',
 'OPEN',
 '2026-01-23 13:31:22',
 '2026-01-23 15:02:48',
 'cmm09k0yo0000yhlkn8u71cqn'),

('Slow query performance on reports endpoint',
 'The reports endpoint experiences significant latency when processing large datasets, sometimes exceeding 15 seconds per request. Query analysis reveals missing indexes on frequently filtered columns, resulting in full table scans under heavy load.',
 'WIP',
 '2026-01-24 09:57:06',
 '2026-01-24 12:18:39',
 'cmm09nhyv0001yhlki9pdgkdw');